version: 2.1

jobs:
  build_conda_package:
    parameters:
      python_version:
        type: string
      cuda_major_version:
        type: string
      cuda_minor_version:
        type: string
    environment:
      PYTHON_VERSION: << parameters.python_version >>
      CUDA_MAJOR_VERSION: << parameters.cuda_major_version >>
      CUDA_MINOR_VERSION: << parameters.cuda_minor_version >>
    docker:
      - image: pytorch/conda-builder:cuda<< parameters.cuda_major_version >><< parameters.cuda_minor_version >>
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Build conda package
          no_output_timeout: 30m
          command: packaging/conda.sh

  trigger_benchmark:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ea:41:e6:ad:56:ad:7b:87:82:a9:aa:34:fe:0d:ff:e2"
      - run:
          name: Trigger benchmark
          command: |
            set -ex
            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
            echo "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=" >> ~/.ssh/known_hosts
            echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> ~/.ssh/known_hosts
            REPO_DIR=$(mktemp -d)
            git clone "$BENCHMARK_REPO" "$REPO_DIR"
            cd "$REPO_DIR" || exit
            git checkout benchmarks
            git submodule update --init --recursive
            cd fairring || exit
            git fetch origin
            git checkout "$CIRCLE_SHA1"
            cd .. || exit
            git add fairring
            git config --global user.email "lcw@fb.com"
            git config --global user.name "Luca Wehrstedt"
            git commit -m "Update to https://github.com/facebookresearch/fairring/commit/$CIRCLE_SHA1"
            git push origin benchmarks


workflows:
  nightly:
    when:
      and:
        - equal: [ main, << pipeline.git.branch >> ]
        # - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        # - equal: [ "nightly", << pipeline.schedule.name >> ]

    jobs:
      - trigger_benchmark
      - build_conda_package:
          name: conda_py3.7_cuda10.2
          python_version: '3.7'
          cuda_major_version: '10'
          cuda_minor_version: '2'
      - build_conda_package:
          name: conda_py3.8_cuda10.2
          python_version: '3.8'
          cuda_major_version: '10'
          cuda_minor_version: '2'
      - build_conda_package:
          name: conda_py3.9_cuda10.2
          python_version: '3.9'
          cuda_major_version: '10'
          cuda_minor_version: '2'
      - build_conda_package:
          name: conda_py3.10_cuda10.2
          python_version: '3.10'
          cuda_major_version: '10'
          cuda_minor_version: '2'
      - build_conda_package:
          name: conda_py3.7_cuda11.1
          python_version: '3.7'
          cuda_major_version: '11'
          cuda_minor_version: '1'
      - build_conda_package:
          name: conda_py3.8_cuda11.1
          python_version: '3.8'
          cuda_major_version: '11'
          cuda_minor_version: '1'
      - build_conda_package:
          name: conda_py3.9_cuda11.1
          python_version: '3.9'
          cuda_major_version: '11'
          cuda_minor_version: '1'
      - build_conda_package:
          name: conda_py3.10_cuda11.1
          python_version: '3.10'
          cuda_major_version: '11'
          cuda_minor_version: '1'
      - build_conda_package:
          name: conda_py3.7_cuda11.3
          python_version: '3.7'
          cuda_major_version: '11'
          cuda_minor_version: '3'
      - build_conda_package:
          name: conda_py3.8_cuda11.3
          python_version: '3.8'
          cuda_major_version: '11'
          cuda_minor_version: '3'
      - build_conda_package:
          name: conda_py3.9_cuda11.3
          python_version: '3.9'
          cuda_major_version: '11'
          cuda_minor_version: '3'
      - build_conda_package:
          name: conda_py3.10_cuda11.3
          python_version: '3.10'
          cuda_major_version: '11'
          cuda_minor_version: '3'
      - build_conda_package:
          name: conda_py3.7_cuda11.5
          python_version: '3.7'
          cuda_major_version: '11'
          cuda_minor_version: '5'
      - build_conda_package:
          name: conda_py3.8_cuda11.5
          python_version: '3.8'
          cuda_major_version: '11'
          cuda_minor_version: '5'
      - build_conda_package:
          name: conda_py3.9_cuda11.5
          python_version: '3.9'
          cuda_major_version: '11'
          cuda_minor_version: '5'
      - build_conda_package:
          name: conda_py3.10_cuda11.5
          python_version: '3.10'
          cuda_major_version: '11'
          cuda_minor_version: '5'
