version: 2.1

jobs:
  build_conda_package:
    parameters:
      python_version:
        type: string
      cuda_major_version:
        type: string
      cuda_minor_version:
        type: string
    environment:
      PYTHON_VERSION: << parameters.python_version >>
      CUDA_MAJOR_VERSION: << parameters.cuda_major_version >>
      CUDA_MINOR_VERSION: << parameters.cuda_minor_version >>
    docker:
      - image: pytorch/conda-builder:cuda<< parameters.cuda_major_version >><< parameters.cuda_minor_version >>
    resource_class: 2xlarge
    steps:
      - checkout
      - run:
          name: Build conda package
          no_output_timeout: 30m
          command: packaging/conda.sh

workflows:
  nightly:
    when:
      and:
        - equal: [ main, << pipeline.git.branch >> ]
        # - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        # - equal: [ "nightly", << pipeline.schedule.name >> ]

    jobs:
      - build_conda_package:
          name: conda_py3.7_cuda10.2
          python_version: '3.7'
          cuda_major_version: '10'
          cuda_minor_version: '2'
      - build_conda_package:
          name: conda_py3.8_cuda10.2
          python_version: '3.8'
          cuda_major_version: '10'
          cuda_minor_version: '2'
      - build_conda_package:
          name: conda_py3.9_cuda10.2
          python_version: '3.9'
          cuda_major_version: '10'
          cuda_minor_version: '2'
      # - build_conda_package:
      #     name: conda_py3.10_cuda10.2
      #     python_version: '3.10'
      #     cuda_major_version: '10'
      #     cuda_minor_version: '2'
      - build_conda_package:
          name: conda_py3.7_cuda11.1
          python_version: '3.7'
          cuda_major_version: '11'
          cuda_minor_version: '1'
      - build_conda_package:
          name: conda_py3.8_cuda11.1
          python_version: '3.8'
          cuda_major_version: '11'
          cuda_minor_version: '1'
      - build_conda_package:
          name: conda_py3.9_cuda11.1
          python_version: '3.9'
          cuda_major_version: '11'
          cuda_minor_version: '1'
      # - build_conda_package:
      #     name: conda_py3.10_cuda11.1
      #     python_version: '3.10'
      #     cuda_major_version: '11'
      #     cuda_minor_version: '1'
      - build_conda_package:
          name: conda_py3.7_cuda11.3
          python_version: '3.7'
          cuda_major_version: '11'
          cuda_minor_version: '3'
      - build_conda_package:
          name: conda_py3.8_cuda11.3
          python_version: '3.8'
          cuda_major_version: '11'
          cuda_minor_version: '3'
      - build_conda_package:
          name: conda_py3.9_cuda11.3
          python_version: '3.9'
          cuda_major_version: '11'
          cuda_minor_version: '3'
      # - build_conda_package:
      #     name: conda_py3.10_cuda11.3
      #     python_version: '3.10'
      #     cuda_major_version: '11'
      #     cuda_minor_version: '3'
      - build_conda_package:
          name: conda_py3.7_cuda11.5
          python_version: '3.7'
          cuda_major_version: '11'
          cuda_minor_version: '5'
      - build_conda_package:
          name: conda_py3.8_cuda11.5
          python_version: '3.8'
          cuda_major_version: '11'
          cuda_minor_version: '5'
      - build_conda_package:
          name: conda_py3.9_cuda11.5
          python_version: '3.9'
          cuda_major_version: '11'
          cuda_minor_version: '5'
      - build_conda_package:
          name: conda_py3.10_cuda11.5
          python_version: '3.10'
          cuda_major_version: '11'
          cuda_minor_version: '5'
